language: python
python:
  - "3.5"

install:
  - pip install -r requirements.txt

script: 
  - python -m pytest --cov-report term-missing --cov=app

after_success:
  - coverage --source='.' 
  - coveralls

cache: pip