FORMAT: 1A
HOST: https://bookameal2.docs.apiary.io/#

# Book A Meal API

Book-A-Meal is an application that allows customers to make food orders and helps the food vendor know what the customers want to eat. This tracking helps keep work in order.
Find it on https://bevkololi.github.io or clone the files from https://github.com/bevkololi/Book-A-Meal.git. You can then open index.html file on your browser.

# Allowed HTTPS Requests

+ PUT     : To modify users, orders and menu 
+ POST    : To create users, meals orders and menu, and also sign up an login
+ GET     : To get meals, orders and menu
+ DELETE  : To delete meals, orders and menu using their id

# Description Of Usual Server Responses:

+ 200 OK - the request was successful.

+ 201 Created - the request was successful and a resourc (meal, user) was created.

+ 202 Accepted - After user sign up

+ 204 No Content - the request was successful but there is no representation to return (i.e. the response is empty).

+ 400 Bad Request - the request could not be understood or was missing required parameters.

+ 401 Unauthorized - authentication failed or user doesn't have permissions for requested operation.

+ 404 Not Found - resource was not found.

+ 405 Method Not Allowed - requested method is not supported for resource.



## User Signup [/auth/signup]

### User sign up [POST]

+ Request (application/json)


        {
            "username": "Bev Kololi",
            "email": "bev@gmail.com",
            "password": "pass1234"
        } 


+ Response 201 (application/json)

    + Headers

            Location: /auth/signup

    + Body

            {
            "message": "New user created!"
            }
            
## User Login [/auth/login]

### User sign up [POST]

+ Request (application/json)


        {
            "username": "Bev Kololi",
            "email": "bev@gmail.com",
            "password": "pass1234"
        } 


+ Response 200 (application/json)

    + Headers

            Location: /auth/signup

    + Body

            {
            "message": "Login successful!!"
            }

## Meals [/api/v1/meals]

### Add meals [POST]

+ Request (application/json)


        {
                "id": 2,
                "name": "Rice and beef",
                "ingredients": "Cooked rice, salad, stewed beef",
                "price": 320,
        } 


+ Response 201 (application/json)

    + Headers

            Location: /api/v1/meals

    + Body

            {
            "meal": meal
            }

### Get meals [GET]

+ Response 201 (application/json)


        {
                "id": 2,
                "name": "Rice and beef",
                "ingredients": "Cooked rice, salad, stewed beef",
                 "price": 320,
        }
        
## Orders [/api/v1/orders]

### Add orders [POST]

+ Request (application/json)


        {       "order_id": 1, 
                "username": "Angie Kihara", 
                "meal": "Pilau and chicken", 
                "quantity": 2
        } 


+ Response 201 (application/json)

    + Headers

            Location: /api/v1/orders

    + Body

            {
            "order": order
            }

### Get order [GET]

+ Response 201 (application/json)


        {       "order_id": 1, 
                "username": "Angie Kihara", 
                "meal": "Pilau and chicken", 
                "quantity": 2
        }